name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t rgazizulin/skypro_todolist_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push rgazizulin/skypro_todolist_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build_and_push
#    env:
#      DEBUG: ${{ secrets.DEBUG }}
#      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
